Enabill.Web/Models/Time/CurrentTimeBalanceModel.cs
using System;
using System.Linq;
using Enabill.Models;

namespace Enabill.Web.Models
{
	public class CurrentTimeBalanceModel
	{
		#region INITIALIZATION

		public CurrentTimeBalanceModel(User user)
		{
			this.CurrentDayTotal = this.LoadDayTotal(user);
			this.CurrentDayBalance = this.CurrentDayTotal - user.WorkHours;
			this.CurrentDayBalanceClass = this.LoadClassForBalance(this.CurrentDayBalance);

			this.MonthTotal = this.LoadMonthTotal(user);  //total hours worked
			this.MonthLeave = this.LoadMonthLeave(user);  //total leave taken/approved
			this.MonthGoalToDate = this.LoadMonthGoalToDate(user) - this.MonthLeave;    //total goal hours
			this.MonthBalance = this.MonthTotal - this.MonthGoalToDate;
			this.MonthBalanceClass = this.LoadClassForBalance(this.MonthBalance);
		}

		#endregion INITIALIZATION

		#region PROPERTIES

		public double CurrentDayBalance { get; private set; }
		public double CurrentDayTotal { get; private set; }
		public double MonthBalance { get; private set; }
		public double MonthGoalToDate { get; private set; }
		public double MonthLeave { get; private set; }
		public double MonthTotal { get; private set; }

		public string CurrentDayBalanceClass { get; private set; }
		public string MonthBalanceClass { get; private set; }
		public string MonthBalanceName { get; private set; }

		#endregion PROPERTIES

		#region FUNCTIONS

		private string LoadClassForBalance(double balance) => balance < 0 ? "error" : "information";

		private double LoadDayTotal(User user)
		{
			var today = user.GetWorkAllocations(DateTime.Today);
			double balance = today.Sum(w => w.HoursWorked);

			return balance;
		}

		private double LoadMonthTotal(User user)
		{
			var monthStart = DateTime.Now.ToFirstDayOfMonth();
			var monthEnd = DateTime.Now.ToLastDayOfMonth();
			var month = user.GetWorkAllocations(monthStart, monthEnd);
			double balance = month.Sum(w => w.HoursWorked);

			return balance;
		}

		private double LoadMonthLeave(User user)
		{
			var monthStart = DateTime.Now.ToFirstDayOfMonth();
			var monthEnd = DateTime.Now.ToLastDayOfMonth();
			double leave = user.GetLeaveTakenTotalInHoursForDateSpan(ApprovalStatusType.Approved, monthStart, monthEnd);

			return leave;
		}

		private double LoadMonthGoalToDate(User user)
		{
			var monthStart = DateTime.Now.ToFirstDayOfMonth();
			var monthEnd = DateTime.Now;

			var workDays = WorkDay.GetWorkableDays(true, monthStart, monthEnd);

			double goal = (workDays.Count * user.WorkHours);

			return goal;
		}

		#endregion FUNCTIONS
	}
}

Enabill.Web/Models/Time/TimeApproveIndexModel.cs
using System;
using System.Collections.Generic;
using Enabill.Models;
using Enabill.Models.Dto;

namespace Enabill.Web.Models
{
	public class TimeApproveIndexModel
	{
		#region INITIALIZATION

		public TimeApproveIndexModel(User user, DateTime dateFrom, DateTime dateTo, string callingPage, int invoiceID = 0)
		{
			var userExceptionDetails = new List<WorkAllocationExceptionModel>();
			//user.IsTimeCaptured(dateFrom, dateTo, user, out userExceptionDetails);
			//DateFrom = InputHistory.GetDateTime(HistoryItemType.ApprovalDateFrom, DateTime.Today.ToFirstDayOfMonth()).Value;
			//DateTo = InputHistory.GetDateTime(HistoryItemType.ApprovalDateTo, DateTime.Today.ToLastDayOfMonth()).Value;
			this.DateFrom = dateFrom;
			this.DateTo = dateTo;
			this.TimeApprovalUser = InputHistory.Get(HistoryItemType.TimeApprovalUser, 0);
			this.InvoiceID = invoiceID;
			this.CallingPage = callingPage;
			this.StandardAmtColumns = 9; // if column are added are removed from the viw, change this value
			this.User = user;
			this.WorkDay = dateFrom;
			this.LoadCalendar(user, dateFrom, dateTo);
			this.CanTimesheetLockStatusBeManaged = user.CanTimesheetLockStatusBeManaged(dateFrom);
			this.IsTimesheetLocked = true;

			if (this.CanTimesheetLockStatusBeManaged)
				this.IsTimesheetLocked = user.IsTimesheetLockedForDate(dateFrom);

			this.TotlAmtColumns = this.StandardAmtColumns + this.ActivityList.Count;
		}

		#endregion INITIALIZATION

		#region PROPERTIES

		public bool CanTimesheetLockStatusBeManaged { get; private set; }
		public bool IsTimesheetLocked { get; private set; }

		public int ApprovalStatus { get; private set; }
		public int InvoiceID { get; private set; }
		public int StandardAmtColumns { get; private set; }
		public int TimeApprovalUser { get; private set; }
		public int TotlAmtColumns { get; private set; }

		public string CallingPage { get; private set; }

		public DateTime DateFrom { get; private set; }
		public DateTime DateTo { get; private set; }
		public DateTime WorkDay { get; private set; }

		public User User { get; private set; }

		public Dictionary<int, string> ActivityList { get; private set; }
		public Dictionary<int, string> NoWorkSessionActivityList { get; private set; }

		public List<ActivityDetail> ActivityDetails { get; private set; }
		public List<TimeCalendarModel> Calendar { get; private set; }

		#endregion PROPERTIES

		#region FUNCTIONS

		private void LoadCalendar(User user, DateTime dateFrom, DateTime dateTo)
		{
			this.ActivityList = new Dictionary<int, string>();

			//if (dateFrom < user.EmployStartDate)
			//    dateFrom = user.EmployStartDate;

			this.ActivityDetails = user.GetWorkedActivitiesForDateSpan(dateFrom, dateTo);

			this.ActivityDetails.ForEach(a => this.ActivityList.Add(a.ActivityID, string.Format($"{a.ClientName}<br />{a.ProjectName}<br />{a.ActivityName}")));

			//user.GetWorkedActivitiesForDateSpan(dateFrom, dateTo.AddDays(1))
			//            .ForEach(a => ActivityList.Add(a.ActivityID, string.Format($"{a.ClientName}<br />{a.ProjectName}<br />{a.ActivityName}")));

			this.Calendar = new List<TimeCalendarModel>();
			Enabill.Helpers.GetDaysInDateSpan(dateFrom, dateTo).ForEach(w => this.Calendar.Add(new TimeCalendarModel(user, w, this.ActivityList)));
		}

		#endregion FUNCTIONS
	}
}

Enabill.Web/Models/Time/TimeApproveUserIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Enabill.Models;
using Enabill.Repos;

namespace Enabill.Web.Models
{
	public class TimeApproveUserIndexModel
	{
		#region INITIALIZATION

		public TimeApproveUserIndexModel(DateTime dateFrom, DateTime dateTo, int managerID)
		{
			this.DateFrom = InputHistory.GetDateTime(HistoryItemType.ApprovalDateFrom, DateTime.Today.ToFirstDayOfMonth()).Value;
			this.DateTo = InputHistory.GetDateTime(HistoryItemType.ApprovalDateTo, DateTime.Today.ToLastDayOfMonth()).Value;

			if (managerID == 0)
				this.TimeUsers = UserRepo.GetAll().OrderBy(u => u.FirstName).ThenBy(ul => ul.LastName).ToList();
			else
				this.TimeUsers = UserRepo.GetStaffForManager(managerID).OrderBy(u => u.FirstName).ThenBy(ul => ul.LastName).ToList();
		}

		#endregion INITIALIZATION

		#region PROPERTIES

		public int TimeApprovalUser { get; private set; }

		public DateTime DateFrom { get; private set; }
		public DateTime DateTo { get; private set; }

		public List<User> TimeUsers { get; private set; }

		#endregion PROPERTIES
	}
}

Enabill.Web/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Enabill.Emailing;
using Enabill.Models;
using Enabill.Models.Dto;
using Enabill.Properties;
using Enabill.Repos;
using Enabill.Repository.Interfaces;
using Enabill.Web.Models;
using ServiceStack;

namespace Enabill.Web.Controllers
{
	[Authorize]
	public class TimeController : BaseController
	{
		private IUserRepository userRepository;

		public TimeController()
		{
		}

		public TimeController(IUserRepository userRepository)
		{
			this.userRepository = userRepository;
		}

		[HttpGet]
		public ActionResult Index(int? id)
		{
			var user = this.CurrentUser;

			if (id.HasValue)
				user = UserRepo.GetByID(id.Value);

			if (user == null)
				return this.ErrorView(new ErrorModel(Resources.ERR_NoUser_Message));

			if (this.CurrentUserID != user.UserID && !this.CurrentUser.CanManage(user))
			{
				return this.ErrorView(new ErrorModel(Resources.ERR_NoPermissionToViewPage_Message, true));
			}

			if (!user.HasRole(UserRoleType.TimeCapturing))
			{
				if (user.UserID == this.CurrentUserID)
					return this.ErrorView(new ErrorModel(Resources.ERR_NoPermissionToViewPage_Message, true));
				else // if (user.UserID != CurrentUserID)
					return this.ErrorView(new ErrorModel(string.Format(Resources.ERR_NonTimeCapturerUser_Message, user.FullName, user.FirstName), true));
			}

			Settings.Current.ContextUser = user;
			this.ViewData["MonthList"] = Helpers.GetDropDownOfMonths(Settings.SiteStartDate, DateTime.Today.ToFirstDayOfMonth().AddMonths(1)).OrderByDescending(x => x.Key).Select(x => new SelectListItem() { Value = x.Key.ToString(), Text = x.Value, Selected = x.Key.IsInCurrentMonth() });

			var model = new TimeIndexModel(user, InputHistory.GetDateTime(HistoryItemType.WorkDay, DateTime.Today).Value);

			return this.View(model);
		}

		[HttpPost]
		public ActionResult Index(FormCollection form)
		{
			try
			{
				var monthYear = form["MonthList"].ToDate();
				int? userID = form["User"].ToInt();
				var user = UserRepo.GetByID(userID.Value);

				if (user == null)
					return this.ErrorView(new ErrorModel(Resources.ERR_NoUser_Message));

				if (this.CurrentUserID != user.UserID && !this.CurrentUser.CanManage(user))
				{
					return this.ErrorView(new ErrorModel(Resources.ERR_NoPermissionToViewPage_Message, true));
				}

				if (!user.HasRole(UserRoleType.TimeCapturing))
				{
					if (user.UserID == this.CurrentUserID)
						return this.ErrorView(new ErrorModel(Resources.ERR_NoPermissionToViewPage_Message, true));
					else
						return this.ErrorView(new ErrorModel(string.Format(Resources.ERR_NonTimeCapturerUser_Message, user.FullName, user.FirstName), true));
				}

				this.ViewData["MonthList"] = Helpers.GetDropDownOfMonths(Settings.SiteStartDate, DateTime.Today.ToFirstDayOfMonth().AddMonths(1)).OrderByDescending(x => x.Key).Select(x => new SelectListItem() { Value = x.Key.ToString(), Text = x.Value, Selected = x.Key == monthYear.Value });

				var model = new TimeIndexModel(user, monthYear.Value);

				return this.View(model);
			}
			catch (Exception ex)
			{
				return this.ReturnJsonException(ex);
			}
		}

		#region DAY

		[HttpGet]
		public ActionResult Day(int? id, string dateString, string callingPage = "")
		{
			var user = this.ContextUser;
			DateTime date;

			var userPref = user.GetUserPreference();
			if (!userPref.DayView)
				return this.RedirectToAction("Week", new { id, dateString, userPref.ThreeState, callingPage });

			if (id.HasValue && id.Value != user.UserID)
				user = UserRepo.GetByID(id.Value);

			if (user == null)
				return this.ErrorView(new ErrorModel(Resources.ERR_NoUser_Message));

			if (this.CurrentUserID != user.UserID && !this.CurrentUser.CanManage(user))
			{
				return this.ErrorView(new ErrorModel(Resources.ERR_NoPermissionToViewPage_Message, true));
			}

			Settings.Current.ContextUser = user;

			if (dateString.ToDate().HasValue)
				date = dateString.ToDate().Value;
			else
				date = DateTime.Today;

			InputHistory.Set(HistoryItemType.WorkDay, date);

			var model = new TimeDayModel(user, date, callingPage);
			this.SetViewDataLists(model);

			return this.View(model);
		}

		[HttpPost]
		public ActionResult SelectDay(string dateString)
		{
			try
			{
				var user = this.ContextUser;
				var date = InputHistory.GetDateTime(HistoryItemType.WorkDay, DateTime.Today).Value;

				if (dateString.ToDate().HasValue)
					date = dateString.ToDate().Value;

				InputHistory.Set(HistoryItemType.WorkDay, date);
				var model = new TimeDayModel(user, date);

				this.SetViewDataLists(model);

				return this.PartialView("ucDay", model);
			}
			catch (Exception ex)
			{
				return this.ReturnJsonException(ex);
			}
		}

		[HttpPost]
		public ActionResult SaveNextDay(DateTime dayToCopy, string previous)
		{
			try
			{
				var user = this.ContextUser;
				bool isPrevious = previous == "true";
				var date = InputHistory.GetDateTime(HistoryItemType.WorkDay, DateTime.Today).Value;

				UserRepo.SaveNextWorkDay(user.UserID, dayToCopy, isPrevious);

				InputHistory.Set(HistoryItemType.WorkDay, date);
				var model = new TimeDayModel(user, date);

				this.SetViewDataLists(model);

				return this.PartialView("ucDay", model);
			}
			catch (Exception ex)
			{
				return this.ReturnJsonException(ex);
			}
		}

		private double HoursWorkedOnDay(ActivityPostModel log, DateTime date)
		{
			switch (date.DayOfWeek)
			{
				case DayOfWeek.Monday:
					return log.Monday;

				case DayOfWeek.Tuesday:
					return log.Tuesday;

				case DayOfWeek.Wednesday:
					return log.Wednesday;

				case DayOfWeek.Thursday:
					return log.Thursday;

				case DayOfWeek.Friday:
					return log.Friday;

				case DayOfWeek.Saturday:
					return log.Saturday;

				default:
					return log.Sunday;
			}
		}

		#endregion DAY

		#region WEEK

		[HttpGet]
		public ActionResult Week(int? id, string dateString, string threeState, string callingPage = "")
		{
			var user = this.ContextUser;
			DateTime date;

			if (id.HasValue && id.Value != user.UserID)
				user = UserRepo.GetByID(id.Value);

			if (user == null)
				return this.ErrorView(new ErrorModel(Resources.ERR_NoUser_Message));

			if (this.CurrentUserID != user.UserID && !this.CurrentUser.CanManage(user))
				return this.ErrorView(new ErrorModel(Resources.ERR_NoPermissionToViewPage_Message, true));

			Settings.Current.ContextUser = user;

			if (dateString.ToDate().HasValue)
				date = dateString.ToDate().Value;
			else
				date = DateTime.Today;

			date = date.AddDays(-(int)date.DayOfWeek + 1); // reset date to earliest monday of the week you selected;
			InputHistory.Set(HistoryItemType.WorkDay, date);

			var userPref = user.GetUserPreference();

			var model = new TimeWeekModel(user, date, userPref.ThreeState, callingPage);

			this.SetViewDataLists(model);

			return this.View(model);
		}

		[HttpPost]
		public JsonResult Week(FormCollection formData)
		{
			bool mustHaveRemarks = formData["mustHaveRemarks"].ToBool() == true;
			int? activityId = formData["activityId"].ToInt();
			int workSessionCount = 0;
			double hrsLogged = 0;
			string remark = "";
			string threeState = formData["filter"];

			if (activityId == null)
				throw new Exception("An error has occured. No values specified for Activity and Hours logged!");

			if (formData["column"] == "Remark")
			{
				hrsLogged = formData["editedDayTime"].ToDouble() ?? 0;
				remark = formData["value"];
			}
			else
			{
				hrsLogged = formData["value"].ToDouble() ?? 0;
				remark = formData["remark"];
			}

			if (hrsLogged > 0 && mustHaveRemarks && remark.IsNullOrEmpty())
			{
				string error = "A remark is required.";

				return this.Json(error);
			}

			var date = (DateTime)formData["startDate"].ToDate(); // this will always be monday's date;
			var day = (DayOfWeek)Enum.Parse(typeof(DayOfWeek), formData["editedDay"]);
			var user = this.ContextUser;
			date = date.AddDays(formData["editedDay"] != "Sunday" ? (int)day - 1 : 6); // get the date of the day values entered in for;

			if (this.CurrentUserID != user.UserID && !this.CurrentUser.CanManage(user))
			{
				string error = "ERROR";

				return this.Json(error);
			}

			try
			{
				var workSessions = user.GetWorkSessions(date);
				workSessionCount = workSessions.Count;

				if (workSessionCount == 0)
				{
					var userPref = user.GetUserPreference();
					double workDayHoursBefore = UserRepo.GetWorkSessionsForDate(user.UserID, date).ToList().Sum(ws => ws.TotalTime);
					double flexiBalanceBefore = user.GetFlexiBalance(date.AddMonths(1).ToFirstDayOfMonth()) == null ? 0 : user.GetFlexiBalance(date.AddMonths(1).ToFirstDayOfMonth()).FinalBalance;

					var d = userPref.DefaultWorkSessionStartTime;
					var startTime = new DateTime(date.Year, date.Month, date.Day, d.Value.Hour, d.Value.Minute, d.Value.Second);
					d = userPref.DefaultWorkSessionEndTime;
					double lunchTime = userPref.DefaultLunchDuration;
					var endTime = startTime.AddHours(hrsLogged + lunchTime);

					user.CaptureWorkSession(this.CurrentUser, startTime, endTime, lunchTime);
					user.CreateBalanceAuditTrail("Worksession", date, user, workDayHoursBefore, flexiBalanceBefore, this.CurrentUser, "added");

					var workSessionList = user.GetWorkSessions(date);
					var userWorkAllocationExceptionList = new List<WorkAllocationExceptionModel>();

					foreach (var ws in workSessionList)
					{
						ws.WorkSessionStatusID = (int)WorkSessionStatusType.UnApproved;
						user.UpdateWorkSession(this.CurrentUser, ws);
					}
				}

				string ticketReference = null; //form["Ticket" + ID];  must set this as well; ????

				var wa = new WorkAllocation
				{
					UserID = user.UserID,
					ActivityID = (int)activityId,
					DayWorked = date,
					Remark = remark,
					HoursWorked = hrsLogged,
					WorkAllocationType = (int)WorkAllocationType.UserCreated
				};

Enabill.Web/Views/Time/ApproveIndex.cshtml
@model Enabill.Web.Models.TimeApproveIndexModel

@section head{
    @IncludeControllerScript(true)
}

@{
    ViewBag.Title = "Timesheet Approval";
}

<div id="ucApproveIndex" class="marginView">
    @Html.Partial("ucApproveIndex", Model)
</div>

Enabill.Web/Views/Time/Day.cshtml
@model Enabill.Web.Models.TimeDayModel

@section beginhead{
    @IncludeRichEditor()
}

@section head{
    @IncludeControllerScript(true)
}

@{
    Html.EnableClientValidation(false);
    ViewBag.Title = Model.User.FullName + "'s Daily Timesheet";
}

<div id="ucDay" class="marginView">
    @Html.Partial("ucDay", Model)
</div>

Enabill.Web/Views/Time/ucActivityIndexCol5.cshtml
@model string

<div class="actionDiv" onclick="window.location= '/Report/ActivityReportIndex/?callingPage=activity'">
    <span class="imageWithText">
        <img alt="" height="16px" src="@Url.Content("~/Content/Img/redo_16x16.png")" />
    </span>
    Go back to Activity Report
</div>

Enabill.Web/Views/Time/ucApproveUserIndex.cshtml
@model Enabill.Web.Models.TimeApproveModel
@{
    var managerList = new Dictionary<int, string>{
{0, "All Staff"},
{CurrentUserID, "My Staff"}
};
}
<table class="headingTable">
    <tbody>
        <tr>
            <td class="headingTableTitle">
                <span class="imageWithText">
                    <img src="/Content/Img/timesheet_20x20.png">
                </span>
                <b>Timesheet Approval User List</b>
            </td>
            <td class=" headingTableRoundingImage">
                &nbsp;
            </td>
            <td class="headingTableCol3"></td>
            <td class="headingTableCol4"></td>
            <td class="headingTableCol5"></td>
        </tr>
    </tbody>
</table>
<div class="padView">
    <table>
        <tr>
            <th>
                <span class="ui-helper-hidden-accessible"><input type="text" /></span>
                Date Range
                @Html.TextBox("DateFrom", Model.DateFrom.ToString("yyyy-MM-dd"))

                to
                @Html.TextBox("DateTo", Model.DateTo.ToString("yyyy-MM-dd"))
            </th>
            <th class="borderRight">
                Manager
                @Html.DropDownList("ManagerList", managerList.Select(t => new SelectListItem { Text = t.Value, Value = t.Key.ToString(), Selected = t.Key == Model.ManagerID }))
            </th>
            <th class="borderRight">
                Status
                @Html.EnumDropDownListFor(m => m.UserWorkDayStatus, "--status")
            </th>
            <th>
                <input type="button" id="btnSearch" value="Search" />
            </th>
        </tr>
    </table>
    <table class="subTable general fullWidth">
        <tr>
            <th width="25%">User Name</th>
            <th width="25%">Full Name </th>
            <th width="5%">Status</th>
            <th width="15%">Exceptions</th>
            <th width="15%">Unapproved</th>
            <th width="15%">Approved</th>
        </tr>
        @foreach (var u in Model.Users.OrderBy(u => u.FullName))
        {
            var className = string.Empty;
            var status = string.Empty;

            if (!u.HasRole(Enabill.UserRoleType.TimeCapturing))
            {
                status = "N/A";
                className = "NA";
            }
            else if (Model.UsersWorkDayModel.Where(uv => uv.User.UserID == u.UserID && uv.HasException).Count() > 0)
            {
                status = "Exception";
                className = "Open";
            }
            else if (Model.UsersWorkDayModel.Where(uv => uv.User.UserID == u.UserID && uv.Status == Enabill.Models.UserWorkDayStatus.Unapproved && uv.WorkDay.IsWorkable).Count() > 0)
            {
                status = "Unapproved";
                className = "Open";
            }
            else if (Model.UsersWorkDayModel.Where(uv => uv.User.UserID == u.UserID && uv.Status == Enabill.Models.UserWorkDayStatus.Approved && uv.WorkDay.IsWorkable).Count() > 0)
            {
                status = "Approved";
                className = "";
            }

            <tr>
                <td>@Html.ActionLink(u.UserName, "ApproveIndex", "Time", new { id = u.UserID, callingPage = "approval" }, null)</td>
                <td>@u.FullName</td>
                <td class="@className">
                    @status
                </td>
                <td>
                    @Model.UsersWorkDayModel.Where(uv => uv.User.UserID == u.UserID && uv.HasException).Count()
                </td>
                <td>
                    @Model.UsersWorkDayModel.Where(uv => uv.User.UserID == u.UserID && uv.Status == Enabill.Models.UserWorkDayStatus.Unapproved && uv.WorkDay.IsWorkable).Count()
                </td>
                <td>
                    @Model.UsersWorkDayModel.Where(uv => uv.User.UserID == u.UserID && uv.Status == Enabill.Models.UserWorkDayStatus.Approved && uv.WorkDay.IsWorkable).Count()
                </td>
            </tr>
        }
    </table>
</div>

Enabill.Web/Views/Time/ucIndex.cshtml
@model Enabill.Web.Models.TimeIndexModel

@Html.TitleTable("tblTimesheet", "", "<b>Timesheet:</b> " + Model.User.FullName, Url.Content("~/Content/Img/timesheet_20x20.png"), "ucIndexCalendar", Model, null, null, null, Model)
<div class="padView">

    <table class="subTable calendarTable fullWidth" style="font-size: 9px;">

        <tr>
            <th width="4%">Weekday</th>
            <th width="4%">Date Worked</th>
            <th width="4%" class="center">Leave</th>
            <th width="4%" class="center">Start</th>
            <th width="4%" class="center">End</th>
            <th width="4%" class="center">Lunch</th>
            <th width="4%" class="center">Hours</th>
            <th width="4%" class="center">Unallocated</th>
            <th width="4% " class="center">Has Notes</th>

            @foreach (var activity in Model.ActivityList)
            {
                <th width="10%" class="center">@Html.Raw(activity.Value)</th>
            }
        </tr>
        @foreach (var day in Model.Calendar)
        {
            <tr class="@day.WorkDayClass">
                <td width="4%">@day.WorkDay.ToString("dddd")</td>
                <td width="4%">
                    @Html.ActionLink(day.WorkDay.ToDisplayString(), "Day", "Time", new { dateString = day.WorkDay.ToDisplayString() }, null)
                </td>
                <td width="4%" class="center">@day.FlexiOrLeaveDayText</td>

                <td width="4%" align="center">
                    @foreach (var ws in day.DailyWorkSessions)
                    {
                        @ws.StartTime.ToString("HH:mm")<br />
                    }
                </td>
                <td width="4%" align="center">
                    @foreach (var ws in day.DailyWorkSessions)
                    {
                        @ws.EndTime.ToString("HH:mm")<br />
                    }
                </td>
                <td width="4%" align="center">
                    @foreach (var ws in day.DailyWorkSessions)
                    {
                        @ws.LunchTime.ToString("0.00")<br />
                    }
                </td>
                <td width="4%" align="center">
                    @foreach (var ws in day.DailyWorkSessions)
                    {
                        @ws.TotalTime.ToString("0.00")<br />
                    }
                </td>
                @{
                    var unallocated = day.User.GetUnallocatedTime(day.WorkDay);
                    string IsZero = string.Empty;
                    if (unallocated != 0)
                    {
                        IsZero = "error";
                    }
                }

                <td width="4%" align="center" class="@IsZero">
                    @if (day.User.GetUnallocatedTime(day.WorkDay) != 0)
                    {
                        @day.User.GetUnallocatedTime(day.WorkDay).ToString("0.00")
                    }
                </td>
                <td width="4%" id="Note@(day.WorkDay.Day)" class="center">

                    @if (day.DayHasNotes)
                    {
                        <img alt="Yes" src="@Url.Content("~/Content/Img/tick_green_small.gif")" height="14px" title="Day Has Notes" />
                    }
                </td>
                @for (int k = 1; k <= Model.ActivityList.Count(); k++)
                {
                    <td width="10%" class="center">
                        @(day.WorkAllocations[k - 1] == 0 ? "" : day.WorkAllocations[k - 1].ToDoubleString())
                    </td>
                }
            </tr>
        }
        <tr>
            <th colspan="5">Total</th>
            <th style="text-align: center !important;">@Model.Calendar.Sum(ws => ws.DailyWorkSessions.Sum(dws => dws.LunchTime)).ToDoubleString()</th>
            <th style="text-align: center !important;">@Model.Calendar.Sum(ws => ws.DailyWorkSessions.Sum(dws => dws.TotalTime)).ToDoubleString()</th>
            <th colspan="2"></th>

            @for (int k = 1; k <= Model.ActivityList.Count(); k++)
            {
                <th style="text-align: center !important;">@Model.Calendar.Sum(ws => ws.WorkAllocations[k - 1]).ToDoubleString()</th>
            }
        </tr>
    </table>
</div>

@Html.Hidden("WorkDay", Model.WorkDay)