Enabill.Web/Controllers/StoryController.cs
using System.Web.Mvc;
using StoryWriter.Models;
using StoryWriter.Services;

namespace Enabill.Web.Controllers
{
	[Authorize]
	public class StoryController : BaseController
	{
		public ActionResult Index() => this.View(StoryService.Search(""));

		public ActionResult Board() => this.View(StoryService.GetAllForProject(EnabillSettings.StoryWriterProjectID));

		[HttpGet]
		public ActionResult Create()
		{
			var story = new Story();
			this.SetViewDropDownLists(story);

			return this.View("Edit", story);
		}

		[HttpGet]
		public ActionResult Page(string id)
		{
			var story = StoryService.GetByRef(id);

			if (story == null)
			{
				story = new Story
				{
					RefUrl = id
				};
			}

			this.SetViewDropDownLists(story);

			return this.View("Edit", story);
		}

		public ActionResult Details(int id)
		{
			var story = StoryService.GetByID(id);

			if (story == null)
				return this.HttpNotFound();

			return this.View(story);
		}

		public ActionResult Preview(string id)
		{
			var story = StoryService.GetByRef(id);

			if (story == null)
			{
				story = new Story
				{
					RefUrl = id
				};
			}

			return this.PartialView(story);
		}

		[HttpGet]
		public ActionResult Edit(int? id)
		{
			var story = StoryService.GetByID(id.Value);

			if (story == null)
				return new HttpNotFoundResult("Story not found");
			this.SetViewDropDownLists(story);

			return this.View(story);
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Edit(int? id, FormCollection form)
		{
			Story story;

			if (id != null)
			{
				story = StoryService.GetByID(id.Value);
			}
			else
			{
				story = new Story
				{
					ProjectID = EnabillSettings.StoryWriterProjectID
				};
			}

			return this.Save(story);
		}

		private ActionResult Save(Story story)
		{
			try
			{
				if (this.TryUpdateModel(story))
				{
					StoryService.Save(story);
					return this.RedirectToAction("Index");
				}
			}
			catch
			{
			}

			this.SetViewDropDownLists(story);

			return this.View(story);
		}

		private void SetViewDropDownLists(Story model)
		{
			this.AddAsDropdownSource(ActorService.GetAll(), "Actor", model.ActorID);
			this.AddAsDropdownSource(StoryGroupService.FetchAllForProject(EnabillSettings.StoryWriterProjectID), "StoryGroup", model.StoryGroupID);
		}
	}
}

Enabill.Web/Views/Story/Board.cshtml
@model IEnumerable<StoryWriter.Models.Story>

    @{
        ViewBag.Title = "Story Board";
    }

    <h1>Story Board | @Html.ActionLink("List", "Index") | @Html.ActionLink("Create New", "Create", "Story") </h1>

    <div class="Story">
        @foreach (var item in Model)
        {
            <h1>
                Story: @item.StoryName (@item.StoryNumber) | @Html.ActionLink("Edit", "Edit", new { id = item.StoryID })
            </h1>
            <div>
                @Html.Raw(item.StoryText)
            </div>

            <div>
                <span class="StoryLines">As a:</span> @item.ActorName<br />
                <span class="StoryLines">I want to:</span> @item.IWantToAction<br />
                <span class="StoryLines">So that:</span> @item.SoThatOutcome<br />
            </div>
            <hr />
        }
    </div>

Enabill.Web/Views/Story/Details.cshtml
@model StoryWriter.Models.Story

@{
    ViewBag.Title = "Details";
}

<h2>Story Details</h2>

<div class="Story">
    <fieldset>
        <legend>Story | @Html.ActionLink("Edit", "Edit", "Story", new { id = Model.StoryID }, null) | @Html.ActionLink("List", "Index") </legend>
        <h2>@Model.StoryName (@Model.StoryNumber)</h2>
        <div>@Html.Raw(Model.StoryText)</div>
        <div>
            <span class="StoryLines">As a:</span> @Model.ActorName<br />
            <span class="StoryLines">I want to:</span> @Model.IWantToAction<br />
            <span class="StoryLines">So that:</span> @Model.SoThatOutcome<br />
        </div>
    </fieldset>
</div>

Enabill.Web/Views/Story/Edit.cshtml
@model StoryWriter.Models.Story

@{
    string action = "Edit";
    if (Model.StoryID == 0)
    {
        action = "Create";
    }

    ViewBag.Title = action;
}

<h2>@action Story | @Html.ActionLink("Go to List", "Index") </h2>

@using (Html.BeginForm("Edit", "Story"))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Story</legend>

        @Html.HiddenFor(model => model.StoryID)

        <div class="editor-label">
            @Html.CleanLabelFor(model => model.StoryName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.StoryName, new { style = "width:500px" })
            @Html.ValidationMessageFor(model => model.StoryName)
        </div>
        <div class="editor-label">
            @Html.CleanLabelFor(model => model.StoryGroupID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StoryGroupID, "StoryGroupList")
            @Html.ValidationMessageFor(model => model.StoryGroupID)
        </div>
        <div class="editor-label">
            @Html.CleanLabelFor(model => model.StoryNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StoryNumber)
            @Html.ValidationMessageFor(model => model.StoryNumber)
        </div>
        <div class="editor-label">
            @Html.CleanLabelFor(model => model.RefUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RefUrl)
            @Html.ValidationMessageFor(model => model.RefUrl)
        </div>
        <div class="editor-label">
            As A
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ActorID, "ActorList")
            @Html.ValidationMessageFor(model => model.ActorID)
        </div>
        <div class="editor-label">
            I want to
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IWantToAction)
            @Html.ValidationMessageFor(model => model.IWantToAction)
        </div>
        <div class="editor-label">
            So that
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoThatOutcome)
            @Html.ValidationMessageFor(model => model.SoThatOutcome)
        </div>
        <div style="margin-top:5px">
            @Html.EditorFor(model => model.StoryText, "HtmlEditor")
            @Html.ValidationMessageFor(model => model.StoryText)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Enabill.Web/Views/Story/Index.cshtml
@model IEnumerable<StoryWriter.Models.DTO.StorySearchResult>
    @{
        ViewBag.Title = "Domain Stories";
    }
    <h2> Domain Stories | @Html.ActionLink("Create New", "Create") | @Html.ActionLink("All Stories", "Board") </h2>
    <table>
        <tr>
            <th></th>
            <th>Story </th>
            <th>Code </th>
            <th>Ref </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.StoryID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.StoryID }) |
                </td>
                <td>
                    @item.StoryName
                </td>
                <td>
                    @item.StoryNumber
                </td>
                <td>
                    @item.RefUrl
                </td>
            </tr>
        }
    </table>

Enabill.Web/Views/Story/Preview.cshtml
@model StoryWriter.Models.Story

@if (Model.StoryID == 0)
{
    <text>No Story exists: <a href="/Story/Page/@Model.RefUrl">Create</a></text>
}
else
{
    <fieldset>
        <legend>Story | @Html.ActionLink("Edit", "Edit", "Story", new { id = Model.StoryID }, null) | <a href="#" onclick="$('#story').hide();return false;">Hide</a> </legend>
        <div class="display-label">StoryName</div>
        <div class="display-field">@Model.StoryName</div>

        <div class="display-label">StoryCode</div>
        <div class="display-field">@Model.StoryNumber</div>
        <div>@Html.Raw(Model.StoryText)</div>

        <div>
            <span class="StoryLines">As a:</span> @Model.ActorName<br />
            <span class="StoryLines">I want to:</span> @Model.IWantToAction<br />
            <span class="StoryLines">So that:</span> @Model.SoThatOutcome<br />
        </div>
    </fieldset>
}